package com.crossing.www.BridgeCrossingWS;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.5.1
 * 2014-10-01T14:46:48.019+01:00
 * Generated source version: 2.5.1
 * 
 */
@WebServiceClient(name = "BridgeCrossingWS", 
                  wsdlLocation = "file:/C:/MuleDemos/Workspace64Win/contractfirstws/src/main/resources/BridgeCrossingPort.wsdl",
                  targetNamespace = "http://www.crossing.com/BridgeCrossingWS/") 
public class BridgeCrossingWS_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.crossing.com/BridgeCrossingWS/", "BridgeCrossingWS");
    public final static QName BridgeCrossingPort = new QName("http://www.crossing.com/BridgeCrossingWS/", "BridgeCrossingPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/MuleDemos/Workspace64Win/contractfirstws/src/main/resources/BridgeCrossingPort.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(BridgeCrossingWS_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/C:/MuleDemos/Workspace64Win/contractfirstws/src/main/resources/BridgeCrossingPort.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public BridgeCrossingWS_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public BridgeCrossingWS_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BridgeCrossingWS_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public BridgeCrossingWS_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public BridgeCrossingWS_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public BridgeCrossingWS_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns BridgeCrossingWS
     */
    @WebEndpoint(name = "BridgeCrossingPort")
    public BridgeCrossingWS getBridgeCrossingPort() {
        return super.getPort(BridgeCrossingPort, BridgeCrossingWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BridgeCrossingWS
     */
    @WebEndpoint(name = "BridgeCrossingPort")
    public BridgeCrossingWS getBridgeCrossingPort(WebServiceFeature... features) {
        return super.getPort(BridgeCrossingPort, BridgeCrossingWS.class, features);
    }

}
