package com.crossing.www.BridgeCrossingWS;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.5.1
 * 2014-10-01T14:46:48.008+01:00
 * Generated source version: 2.5.1
 * 
 */
@WebService(targetNamespace = "http://www.crossing.com/BridgeCrossingWS/", name = "BridgeCrossingWS")
@XmlSeeAlso({ObjectFactory.class})
public interface BridgeCrossingWS {

    @WebResult(name = "out", targetNamespace = "")
    @RequestWrapper(localName = "sendCrossingDetails", targetNamespace = "http://www.crossing.com/BridgeCrossingWS/", className = "com.crossing.www.BridgeCrossingWS.SendCrossingDetails")
    @WebMethod(action = "urn:SendCrossingDetails")
    @ResponseWrapper(localName = "sendCrossingDetailsResponse", targetNamespace = "http://www.crossing.com/BridgeCrossingWS/", className = "com.crossing.www.BridgeCrossingWS.SendCrossingDetailsResponse")
    public java.lang.String sendCrossingDetails(
        @WebParam(name = "vrn", targetNamespace = "")
        java.lang.String vrn,
        @WebParam(name = "gateno", targetNamespace = "")
        java.lang.String gateno,
        @WebParam(name = "direction", targetNamespace = "")
        java.lang.String direction
    );
}
